### PR TITLE
License ?

### PR DESCRIPTION
**Pull request by xantares**
Hello mr. ihsan,

I've been searching for free as in free software implementation of the nback game for android.
Yours is the best so far.
I'd like to improve it and ultimately publish it on fdroid.org.
I couldn't find any licensing infos about this code, would you be willing to release it as free software ?
I'm proposing a permissive BSD license, but I'm fine with GPL too.

Regards,
xantares

### CODE REVIEW

**Comment by asimihsan** [comment]
I'd completely forgotten about dualnback! Thank you for letting me know this is the best free implementation of nback available; I'm sorry I haven't had more time to complete and release this game.

I apologise for not applying a license to this repo. I'm going to apply an MIT license; it is functionally equivalent to the BSD license (2-part and 3-part) just slightly more common and recognisable, that's all. For more information please see: http://choosealicense.com/licenses/

However I'm confused by the large style/whitespace changes that are also part of this pull request. It would be good, if you feel this is important, to make a separate pull request for style/whitespace issues.

**Comment by asimihsan** [comment]
9ca675b applies an MIT license to the `dualnback` codebase.

I'm going to close this issue as resolved. If you feel the style/whitespace issues are important please pull etc.

Please let me know how you get on, progress, and improve the code!

**Comment by xantares** [comment]
Thank you for the quick response!
MIT is good to! I thought BSD was more common. I guess I deal with much python libs.
About the indent, I just wanted to make it consistent, some parts had tabs and some other files were indented by 4-spaces. I'd go for 2-spaces indent, like in good old c++. What do you suggest ? 

xan.

Date: Wed, 16 Apr 2014 10:27:15 -0700

**Comment by xantares** [comment]
Thank you.

I'm going to try to focus on (I'm a beginner on android):
- input handling: get rid of the "both" button, like brainworkshop [1] and color them green/red on success/failure
- percentage of success/failure at the end of the session
- and maybe all the letters is too much, brainworkshop uses only a few (chklqrst), and I could not find more infos on the original paper, maybe a random subset ?
- menu/persistent stats if I get manage to get more time

[1] http://brainworkshop.sourceforge.net/

Date: Wed, 16 Apr 2014 10:33:44 -0700

**Comment by asimihsan** [comment]
> I'm going to try to focus on (I'm a beginner on android):
> - input handling: get rid of the "both" button, like brainworkshop [1] and color them green/red on success/failure

Here is a link to the PDF of the original study:

http://www.pnas.org/content/early/2008/04/25/0801268105.full.pdf#page=1&view=FitH

It's clear the Brainworkshop is correct I was not. Both the audio and visual stimuli must be in sync; you can't repeat audio, video, or both. Hence you could maybe have two buttons ("repetition", "no repetition"), and if the user doesn't answer within a certain amount of time default to "no repetition"?

Looking in [`src/com/gyrovague/dualnback/GameManager.java`](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/GameManager.java#L9) I can see that when I first wrote the code I was confused about this:

```
 * Also note that the original study methodology is vague about what the user response should
 * be when both visual and auditory targets are present.  In my implementation I assume that
 * a distinct, third response is required (i.e. the possible user responses are four-fold:
 * no repetition, audio repetition, visual repetition, and both audio and visual repetition).
```

I think coloring the buttons on success/failure is a great idea. Another idea I had was to briefly flash the whole screen red on failure, and do nothing on success.

> - percentage of success/failure at the end of the session

This is an excellent idea too. Note that people should be allowed to progress to a more difficult level even if they make a few mistakes. The mistakes thresholds are covered by [`src/com/gyrovague/dualnback/GameManager.java`](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/GameManager.java#L64) `LOWER_MISTAKE_LIMIT` and `UPPER_MISTAKE_LIMIT`.

> - and maybe all the letters is too much, brainworkshop uses only a few (chklqrst), and I could not find more infos on the original paper, maybe a random subset ?

Currently every time the game starts we choose a random subset of eight consonants. The code to look at is in [`src/com/gyrovague/dualnback/SoundManager.java`](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/SoundManager.java#L34), specifically the `mConsonantsInUse` variable and the [only constructor](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/SoundManager.java#L51).

> - menu/persistent stats if I get manage to get more time

This would be nice, I've always wanted to do this. It would be good to track accuracy over time (am I getting better?) and time of day (am I better in the morning vs. the evening?).

**Pull request closed without merging**
