### PR TITLE
Guess audio and video separately

### PR DESCRIPTION
**Pull request by xantares**
I succeeded in improving inputs : visual & audio inputs are now independent : no more both button.
the code has been simplified using bitfields.

I also removed the generated R.java and cleaned up remaining tabs.

Next step is stats, then button coloring on success/failure, disabled atm as the button shape was affected.

Looking forward to your review.

### CODE REVIEW

**Comment by asimihsan** [comment]
This is fantastic thanks for your work. Right now I'm on holiday so I'll be able to review this end of next week probably over the weekend. I'd like to run it on a simulator and a real device and check it works etc. 

Good call on removing R.java no way that needs to be there.

**Comment by xantares** [comment]
I'm not quite sure about your method used to decide if we should increase n-back level.
Brainworkshop has a single upper threshold value, which means a guess is correct if both audio & visual guesses are correct, which is a stronger constraint.

**Comment by asimihsan** [comment]
> I'm not quite sure about your method used to decide if we should increase n-back level.

My memory is a bit rusty too, but everything is going to be inside [GameManager.java](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/GameManager.java).

> Brainworkshop has a single upper threshold value, which means a guess is correct if both audio & visual guesses are correct, which is a stronger constraint.

Currently dualnback:
- increments the values for mistakes individually for either audio or visual mistakes (or both) in [GameManager.java :: evaluateGuess()](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/GameManager.java#L122). Then when a block of 20 repetition is finished [GameManager.java :: advanceBlock()](https://github.com/asimihsan/dualnback/blob/master/src/com/gyrovague/dualnback/GameManager.java#L167) decides whether you did good enough to make it harder or easier.
  - `mNInterval++` means make it harder.
  - `mNInterval = Math.max(mNInterval - 1, 1);` means make it easier, but be careful to not make the difficulty negative.

Does that make sense? Notice what's happening inside `advanceBlock()`:
- If you make less than `LOWER_MISTAKE_LIMIT` errors in both audio and visual (current value is 3) make it more difficult by increasing the N interval.
- If you make more than `UPPER_MISTAKE_LIMIT`errors in both audio and visual (current value is 5) make it less difficult by decreasing the N interval, whilst at the same time making sure the N interval is always >= 1.
- Else keep the difficulty the same.

Is this too complicated? It would be simpler if there was just one threshold value, I don't know why I thought having two was necessary.

**Comment by asimihsan** [comment]
> I succeeded in improving inputs : visual & audio inputs are now independent : no more both button. the code has been simplified using bitfields.

I've had a bit of a play with your new code in the simulator and on a device - this is great!

The code review is taking me longer than I expected because my memory of this code is very rusty, it's going to take a bit longer for me to give you useful feedback. Sorry for the delay, please be patient!

**Comment by xantares** [comment]
Now there's a single threshold comparison.
And there's a little tweak : fallback to the N-1 level only after 3 blocks of bad scoring.

**Comment by xantares** [comment]
: /

**Comment by asimihsan** [comment]
What's up? Sorry I've been neglecting this a bit, let me know what're you're working on and your thoughts.

This pull request has become rather large. It's time for me to look at it all and unless I have any comments merge it.

**Comment by xantares** [comment]
Hi,
I've been waiting for your review.

I thinking on making the block length adjustable (brainworkshop use ~30 instead of 20)
That means the audio/video repetitions should be defined as ratios wrt block length instead of arithmetic count.
I tried to look at bw code for generating the random sequence but the code is not well organized.

Then I could look into adding a menu for parameters, stats, an icon would be really cool but I suck at drawing in inkscape, in a separate PR.
But that could really take much more time as I'm really discovering the android api.

xan.

**Comment by xantares** [comment]
But hey, the image is not matching the example comments ;  the's no visual repetition between interval and and 2!
Still got the source image as svg ?

**Comment by asimihsan** [comment]
> Still got the source image as svg ?

Probably not sorry. I drew it in Microsoft Visio! I can work on drawing this again.

**Comment by xantares** [comment]
Yes it was just so boring to redo all these levels back : ]

**Comment by asimihsan** [comment]
I've read through all the code I'm happy with it. I'm going to run through the game a few more times on a test phone and then merge this pull request.

I'll try to respond faster next time, sorry!

Also please note that I've opened a new issue to do with a bad bug to do with sending the game into the background then restoring it.

**Comment by asimihsan** [comment]
> I thinking on making the block length adjustable (brainworkshop use ~30 instead of 20). That means the audio/video repetitions should be defined as ratios wrt block length instead of arithmetic count.

I think it makes sense to have user preferences to make this configurable. Make a separate issue  for this whenever you want to start working on it.

**Comment by asimihsan** [comment]
> Then I could look into adding a menu for parameters, stats, an icon would be really cool but I suck at drawing in inkscape, in a separate PR. But that could really take much more time as I'm really discovering the android api.

I think you should tackle areas of `dualnback` depending on what you're motivated to learn next. Don't worry too much about drawing pretty graphics, we don't need any pretty graphics for now (e.g. charts and icons).

**Pull request merged**
